config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings
  
  get 'pages/about'
  get 'pages/contact'
  get 'pages/mthhome'
  get 'seller' => "listings#seller"
  get 'listview' => "listings#listview"
  get 'listingbycat' => "listings#listingbycat"
  get 'listingbycattable' => "listings#listingbycattable"

  root 'pages#mthhome' 

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file 	:image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "imagenotfound.png"
	else
		has_attached_file 	:image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "imagenotfound.png",
				:storage => :dropbox,
   				:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
   				:path => ":style/:id_:filename"        
  end

  validates :name, :description, presence: true
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]


  def listingbycat 
    @listings = Listing.where("category = ?",params[:category]).order("created_at DESC")
    session[:viewtype] = "list"
    session[:category] = params[:category]
  end

  def listingbycattable
    @listings = Listing.where("category = ?",params[:category]).order("created_at DESC")
    session[:viewtype] = "table"
    session[:category] = params[:category]
  end

  def listview 
    @listings = Listing.all.order("created_at DESC")
    session[:viewtype] = "list"
    session[:category] = "none"
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
    session[:viewtype] = "table"
    session[:category] = "none"
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Item was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :category, :image)
    end

    def check_user
      if not user_signed_in?
        redirect_to root_url, alert: "Sorry, you are not the owner of this item."
      end
    end      
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def mthhome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		sentence = I18n.t('error.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

		html = <<-HTML
		<div class="alert alert-danger alert-dismissable">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  <h4>#{sentence}</h4>
		  #{messages}
		</div>
		HTML

		html.html_safe
	end
end	

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2015</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Monica's Kitchen Creations</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'New Item', new_listing_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Show All as Table", listings_path %></li>
        <li><%= link_to "Show All as List", listview_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <% else %>
            <li><%= link_to "Admin Sign In", new_user_session_path %></li>
        <% end -%>
      </ul>
      
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Bring in the _header partial file from app/view/layouts/header -->

<%= render 'layouts/header' %>

<!-- Dont need links below anymore because we put them in the navbar above -->
<!-- <a href="/pages/about">About</a> -->
<!-- <a href="/pages/contact">Contact</a> -->
<div class="container">
 	<% flash.each do |name, msg| %>
 		<% if msg.is_a?(String) %>
 			<div class="alert alert-<%= name ==:notice ? "success" : "danger" %> alert-dismissable">
 				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
 				<%= content_tag :div, msg, :id => "flash_#{name}" %>
 			</div>
 		<% end %>
 	<% end %>		

  <%= yield %>

  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.radio_button(:category, "Vienesse Pastry") %> <%= f.label(:category_category1, "Vienesse Pastry") %><br>
    <%= f.radio_button(:category, "Cakes and Tortes") %> <%= f.label(:category_category2, "Cakes and Tortes")%> <br>
    <%= f.radio_button(:category, "Plated Desserts") %> <%= f.label(:category_category3, "Plated Desserts") %><br>
    <%= f.radio_button(:category, "Breads, Rolls and Breakfast Pastry") %> <%= f.label(:category_category3, "Breads, Rolls and Breakfast Pastry") %> <br>
    <%= f.radio_button(:category, "Misc") %> <%= f.label(:category_category3, "Misc") %> 
  </div>  
 <hr>
 <div class="form-group">
    <% if @listing.image.exists? %>
      <%= f.label "Current image file name: " %><br>
      <%= image_tag @listing.image_file_name %><br/>
    <% end %>
  </div>  
  <div class="form-group">
    <%= f.label "New image file name: " %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/listings/edit.html.erb
<title>Edit Listing</title>

<%= render 'form' %>

<%= link_to 'Show', @listing, class:"btn btn-link" %> |
<% case session[:viewtype] %>
	<% when 'table' %>
	  <% if session[:category] != "none"%>
	  	<%= link_to 'Back to Listings', listingbycattable_path(category: session[:category]), class:"btn btn-link" %>
	  <% else %>
	  	<%= link_to 'Back to Listings', listings_path, class:"btn btn-link" %>
	  <% end %>
	<% when 'list' %>
	  <% if session[:category] != "none"%>
	  	<%= link_to 'Back to Listings', listingbycat_path(category: session[:category]), class:"btn btn-link" %>
	  <% else %>
	  	<%= link_to 'Back to Listings', listview_path, class:"btn btn-link" %>
	  <% end %>
	<% end %>

app/views/listings/index.html.erb
<br><br><br><br>
<div class="jumbotron" >
  <h1>Monica's Portfolio</h1>
  <h2>Creations from the Kitchen!</h2>
</div>

<div class="center">
  <!-- Below are bootstrap methods to create 4 columns per row  -->
  <div class="row">
   <% @listings.each do |listing| %>
    <div class="col-md-3">
       <div class="thumbnail">
       <%= link_to image_tag(listing.image.url), listing %>   
       
        <div class="caption">
          <h3><%= listing.name %></h3>
          <%= link_to 'Show', listing, class:"btn btn-link" %>
        </div>
      </div>	
    </div>
   <% end %>
  </div>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Item', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/listingbycat.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Category</th>
    <th class="center">Description</th>
    <% if user_signed_in? %>
      <th class="center">Action</th>
    <% end %>  
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to image_tag(listing.image.url(:thumb)), listing %></td> 
      <td><%= listing.name %></td>
      <td><%= listing.category %></td>
      <td><%= listing.description %></td>
      <% if user_signed_in? %>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'View', listing, class:"btn btn-link" %></li>
              <li><%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-link" %></li>
              <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-link"%></li>
            </ul>
          </div>
        </td>
        <% end %>
    </tr>
  <% end %>
</table>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Item', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/listingbycattable.html.erb
<title>All By Category View</title>
<div class="center">
  <!-- Below are bootstrap methods to create 4 columns per row  -->
  <div class="row">
   <% @listings.each do |listing| %>
    <div class="col-md-3">
       <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>   
        <div class="caption">
          <h3><%= listing.name %></h3>
        </div>
      </div>	
    </div>
   <% end %>
  </div>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Item', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/listview.html.erb
<br><br><br><br>
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <% if user_signed_in? %>
      <th class="center">Action</th>
    <% end %>  
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to image_tag(listing.image.url(:thumb)), listing %></td> 
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <% if user_signed_in? %>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'View', listing, class:"btn btn-link" %></li>
              <li><%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-link" %></li>
              <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-link"%></li>
            </ul>
          </div>
        </td>
        <% end %>
    </tr>
  <% end %>
</table>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Item', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<title>New Listing</title>
<h3>New Listing</h3>

<%= render 'form' %>

<% case session[:viewtype] %>
	<% when 'table' %>
	  <% if session[:category] != "none"%>
	  	<%= link_to 'Back to Listings', listingbycattable_path(category: session[:category]), class:"btn btn-link" %>
	  <% else %>
	  	<%= link_to 'Back to Listings', listings_path, class:"btn btn-link" %>
	  <% end %>
	<% when 'list' %>
	  <% if session[:category] != "none"%>
	  	<%= link_to 'Back to Listings', listingbycat_path(category: session[:category]), class:"btn btn-link" %>
	  <% else %>
	  	<%= link_to 'Back to Listings', listview_path, class:"btn btn-link" %>
	  <% end %>
	<% end %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <% if user_signed_in? %>
      <th class="center">Action</th>
    <% end %>  
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <% if user_signed_in? %>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'View', listing, class:"btn btn-link" %></li>
              <li><%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-link" %></li>
              <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-link"%></li>
            </ul>
          </div>
        </td>
        <% end %>
    </tr>
  <% end %>
</table>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Item', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<!-- Create a 2 column table to show the entry.  Col 1 is the image, col2 two is the rest -->
<title>Show Listing</title>
<div class="row">
   <div class="col-md-4">
	<div class="thumbnail">
	  <%= image_tag @listing.image.url %>
	</div>
   </div>
   <div class="col-md-8">
	<h3><%= @listing.name %></h3>
	<h4><%= @listing.category %></h4>
	<p><%= @listing.description %></p>
   </div>			
</div>

<% if user_signed_in? %>
	<%= link_to 'Edit', edit_listing_path(@listing), class:"btn btn-link" %> 
<% end %>

<% case session[:viewtype] %>
	<% when 'table' %>
	  <% if session[:category] != "none"%>
	  	<%= link_to 'Back to Listings', listingbycattable_path(category: session[:category]), class:"btn btn-link" %>
	  <% else %>
	  	<%= link_to 'Back to Listings', listings_path, class:"btn btn-link" %>
	  <% end %>
	<% when 'list' %>
	  <% if session[:category] != "none"%>
	  	<%= link_to 'Back to Listings', listingbycat_path(category: session[:category]), class:"btn btn-link" %>
	  <% else %>
	  	<%= link_to 'Back to Listings', listview_path, class:"btn btn-link" %>
	  <% end %>
	<% end %>
	

app/views/pages/about.html.erb
<title>About</title>
<h2>Welcome to Monica's Kitchen Creations</h2>
<h3>These are some of the things I created while studying at the 
	<a href="http://www.nfculinary.org/" target="_blank" >Niagara Falls Culinary Institute</a>
 and since then in my own kitchen.<br><br>Monica
</h3>

app/views/pages/contact.html.erb
<br>
<title>Contact</title>
<h4>Email me at mheenehan@stny.rr.com</h4>

app/views/pages/mthhome.html.erb
<div class="center" >
<title>Monica's Portfolio</title>
<div class="row">
	<div class="col-xs-6 col-md-3">
	   <div class="medium">
	   	<%= link_to image_tag('https://dl.dropboxusercontent.com/s/uxfxgvdzsakb3dt/vienesse2.png?dl=0'), listingbycattable_path(category: "Vienesse Pastry")%>
	    <div class="caption">
	      <h3><%= "Vienesse Pastry" %></h3>
	    </div>
	  </div>	
	</div>

	<div class="col-xs-6 col-md-3">
	   <div class="medium">
	   	<%= link_to image_tag('https://dl.dropboxusercontent.com/s/ntiigju9muvbxge/3_ctcake.jpg?dl=0'),  listingbycattable_path(category: "Cakes and Tortes")%>
	    <div class="caption">
	      <h3><%= "Cakes and Tortes" %></h3>
	    </div>
	  </div>	
	</div>
	<div class="col-xs-6 col-md-4">
	   <div class="medium">
	    <%= link_to image_tag('https://dl.dropboxusercontent.com/s/sk4v57xuk45rhyy/2_BakedAlaska.jpg?dl=0'), listingbycattable_path(category: "Plated Desserts")%>
	    <div class="caption">
	      <h3><%= "Plated Desserts" %></h3>
	    </div>
	  </div>	
	</div>
	<div class="col-xs-6 col-md-4">
	   <div class="medium">
	   	<%= link_to image_tag('https://dl.dropboxusercontent.com/s/thxj3irv7sn9ve3/rolls2.png?dl=0'), listingbycattable_path(category: "Breads, Rolls and Breakfast Pastry")%>
	    <div class="caption">
	      <h3><%= "Breads, Rolls and Breakfast Pastry" %></h3>
	    </div>
	  </a>	
	</div>
</div>
<br><br>
<div class="row">
	<div class="col-xs-6 col-md-4">
	   <div class="medium">
	   	<%= link_to image_tag('https://dl.dropboxusercontent.com/s/t1qex1mfkh29wnf/misc2.png?dl=0'), listingbycattable_path(category: "Misc")%>
	    <div class="caption">
	      <h3><%= "Misc" %></h3>
	    </div>
	  </div>	
	</div>
</div>
</div>
<br><br>